#!/usr/bin/env python
from __future__ import print_function
import sys
try:
    from PyQt4.QtCore import QCoreApplication
except ImportError:
    print("ERROR: PyQt4 not installed please install it: (i.e sudo apt-get install python-qt4)",
          file=sys.stderr)
    sys.exit(-1)

from qpushbullet import main

if __name__ == '__main__':
        main()
