# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Aug 13 19:33:33 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(549, 371)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.noteTab = QtGui.QWidget()
        self.noteTab.setObjectName(_fromUtf8("noteTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.noteTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 7, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.noteTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.noteTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.sendNoteBtn = QtGui.QPushButton(self.noteTab)
        self.sendNoteBtn.setObjectName(_fromUtf8("sendNoteBtn"))
        self.gridLayout_3.addWidget(self.sendNoteBtn, 7, 1, 1, 1)
        self.noteTextEdt = QtGui.QTextEdit(self.noteTab)
        self.noteTextEdt.setObjectName(_fromUtf8("noteTextEdt"))
        self.gridLayout_3.addWidget(self.noteTextEdt, 5, 0, 1, 2)
        self.noteTitleEdt = QtGui.QLineEdit(self.noteTab)
        self.noteTitleEdt.setObjectName(_fromUtf8("noteTitleEdt"))
        self.gridLayout_3.addWidget(self.noteTitleEdt, 3, 0, 1, 2)
        self.tabWidget.addTab(self.noteTab, _fromUtf8(""))
        self.LinkTab = QtGui.QWidget()
        self.LinkTab.setObjectName(_fromUtf8("LinkTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.LinkTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.LinkTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.LinkTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 3, 0, 1, 1)
        self.sendLinkBtn = QtGui.QPushButton(self.LinkTab)
        self.sendLinkBtn.setObjectName(_fromUtf8("sendLinkBtn"))
        self.gridLayout_7.addWidget(self.sendLinkBtn, 5, 1, 1, 1)
        self.linkUrlEdt = QtGui.QLineEdit(self.LinkTab)
        self.linkUrlEdt.setObjectName(_fromUtf8("linkUrlEdt"))
        self.gridLayout_7.addWidget(self.linkUrlEdt, 4, 0, 1, 2)
        self.linkTitleEdt = QtGui.QLineEdit(self.LinkTab)
        self.linkTitleEdt.setObjectName(_fromUtf8("linkTitleEdt"))
        self.gridLayout_7.addWidget(self.linkTitleEdt, 2, 0, 1, 2)
        self.tabWidget.addTab(self.LinkTab, _fromUtf8(""))
        self.fileTab = QtGui.QWidget()
        self.fileTab.setObjectName(_fromUtf8("fileTab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.fileTab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.filePathEdt = QtGui.QLineEdit(self.fileTab)
        self.filePathEdt.setReadOnly(False)
        self.filePathEdt.setObjectName(_fromUtf8("filePathEdt"))
        self.gridLayout_9.addWidget(self.filePathEdt, 3, 0, 1, 1)
        self.browseFileBtn = QtGui.QPushButton(self.fileTab)
        self.browseFileBtn.setObjectName(_fromUtf8("browseFileBtn"))
        self.gridLayout_9.addWidget(self.browseFileBtn, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 5, 0, 1, 1)
        self.sendFileBtn = QtGui.QPushButton(self.fileTab)
        self.sendFileBtn.setObjectName(_fromUtf8("sendFileBtn"))
        self.gridLayout_9.addWidget(self.sendFileBtn, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.fileTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 6, 0, 1, 1)
        self.tabWidget.addTab(self.fileTab, _fromUtf8(""))
        self.listTab = QtGui.QWidget()
        self.listTab.setObjectName(_fromUtf8("listTab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.listTab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.removeItemBtn = QtGui.QPushButton(self.listTab)
        self.removeItemBtn.setObjectName(_fromUtf8("removeItemBtn"))
        self.gridLayout_10.addWidget(self.removeItemBtn, 4, 1, 1, 2)
        self.addItemBtn = QtGui.QPushButton(self.listTab)
        self.addItemBtn.setObjectName(_fromUtf8("addItemBtn"))
        self.gridLayout_10.addWidget(self.addItemBtn, 3, 1, 1, 2)
        self.itemsList = QtGui.QListWidget(self.listTab)
        self.itemsList.setAlternatingRowColors(True)
        self.itemsList.setObjectName(_fromUtf8("itemsList"))
        self.gridLayout_10.addWidget(self.itemsList, 3, 0, 4, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem5, 6, 2, 1, 1)
        self.sendListBtn = QtGui.QPushButton(self.listTab)
        self.sendListBtn.setObjectName(_fromUtf8("sendListBtn"))
        self.gridLayout_10.addWidget(self.sendListBtn, 7, 2, 1, 1)
        self.clearItemsBtn = QtGui.QPushButton(self.listTab)
        self.clearItemsBtn.setObjectName(_fromUtf8("clearItemsBtn"))
        self.gridLayout_10.addWidget(self.clearItemsBtn, 5, 1, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(289, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 7, 0, 1, 2)
        self.listTitleEdt = QtGui.QLineEdit(self.listTab)
        self.listTitleEdt.setObjectName(_fromUtf8("listTitleEdt"))
        self.gridLayout_10.addWidget(self.listTitleEdt, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.listTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_10.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.listTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_10.addWidget(self.label_7, 2, 0, 1, 1)
        self.tabWidget.addTab(self.listTab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName(_fromUtf8("menu_About"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.devicesList = QtGui.QListWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesList.sizePolicy().hasHeightForWidth())
        self.devicesList.setSizePolicy(sizePolicy)
        self.devicesList.setMinimumSize(QtCore.QSize(100, 0))
        self.devicesList.setObjectName(_fromUtf8("devicesList"))
        self.gridLayout.addWidget(self.devicesList, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_Settings = QtGui.QAction(MainWindow)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))
        self.action_Refresh = QtGui.QAction(MainWindow)
        self.action_Refresh.setObjectName(_fromUtf8("action_Refresh"))
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_About.addAction(self.action_About)
        self.menu_Edit.addAction(self.action_Settings)
        self.menu_Edit.addAction(self.action_Refresh)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.toolBar.addAction(self.action_Refresh)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.devicesList)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QPushBullet", None))
        self.label_2.setText(_translate("MainWindow", "Note", None))
        self.label.setText(_translate("MainWindow", "Title", None))
        self.sendNoteBtn.setText(_translate("MainWindow", "Push Note", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.noteTab), _translate("MainWindow", "Note", None))
        self.label_4.setText(_translate("MainWindow", "Title", None))
        self.label_3.setText(_translate("MainWindow", "Link", None))
        self.sendLinkBtn.setText(_translate("MainWindow", "Push Link", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LinkTab), _translate("MainWindow", "Link", None))
        self.browseFileBtn.setText(_translate("MainWindow", "Browse", None))
        self.sendFileBtn.setText(_translate("MainWindow", "Push File", None))
        self.label_5.setText(_translate("MainWindow", "File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fileTab), _translate("MainWindow", "File", None))
        self.removeItemBtn.setText(_translate("MainWindow", "Remove", None))
        self.addItemBtn.setText(_translate("MainWindow", "Add", None))
        self.sendListBtn.setText(_translate("MainWindow", "Push List", None))
        self.clearItemsBtn.setText(_translate("MainWindow", "Clear", None))
        self.label_6.setText(_translate("MainWindow", "Title", None))
        self.label_7.setText(_translate("MainWindow", "Items", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.listTab), _translate("MainWindow", "List", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_About.setTitle(_translate("MainWindow", "&Help", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Devices", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))
        self.action_Exit.setText(_translate("MainWindow", "&Exit", None))
        self.action_Settings.setText(_translate("MainWindow", "&Settings", None))
        self.action_Refresh.setText(_translate("MainWindow", "&Refresh", None))

